import requests
import os 
# it does conenct and works just fine
'''url_test = "https://api.openai.com/v1/chat/completions"

key =  "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"
headers = \
{
    "Authorization": f"Bearer {key}",
    "Content-Type": "application/json"
}
data = \
{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "write something nice"}]
}
#need to change json to string so it prints out well
response = requests.post(url_test,headers=headers,json=data)

# in the response we look for first response and we take the content of the reply, so it looks readable!

print(response.json()['choices'][0]['message']['content']) 
'''
# otworzenie pliku w folderze, pozniej trzeba bedzie var tekst dac do content by ai go przerobilo
'''with open("resc artykulu.txt",'r') as tresc:
    tekst = tresc.read()

print(tekst)'''
# i dont really want to use my tokens that often so its a testcase first too see if writing to html file works just fine
example_text = "this is a text that is supposed tom be generated by ai but ...  witam wszystkich bardzo serdecznie"
html_format = f"""
<body>
<h1>helloo!</h1>
<p>{example_text}</p>
</body>
"""
with open("artykul.html",'w') as plik:
    plik.write(html_format)